[workspace]
members = ["as-build", "as-boot", "as-kernel", "elf", "bootgfx", "efi"]
default-members = ["as-build", "elf"]
resolver = "3"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
